#!/usr/bin/env bash

fatal() {
    echo fatal: "$@" >&2
    exit 1
}

info() {
    echo info: "$@"
}

if [ "$SKIPSONARLINT" ]; then
    info "SKIPSONARLINT is set, skipping verification..."
    exit 0
fi

if ! which sonarlint &>/dev/null; then
    fatal "cannot find sonarlint. Did you add to PATH?"
fi

against=origin/master...
filter=AM  # see --diff-filter in git diff --help

failures=
files=($(git diff --name-only $against --diff-filter=$filter))
args=()
sources=()
tests=()
for file in "${files[@]}"; do
    if ! [ -f "$file" ]; then
        echo "skip deleted file: $file"
        continue
    fi
    if [[ $file == *src/* ]]; then
        if [[ $file == *src/test/* ]]; then
            tests+=("$file")
            args+=(--tests "$file")
        else
            sources+=("$file")
        fi
        args+=(--src "$file")
        continue
    fi
    echo "skip unknown file: $file"
done

if [ ${#sources} = 0 -a ${#tests} = 0 ]; then
    info no files to analyze
    exit
fi

info "sources: ${sources[@]}"
info "tests: ${tests[@]}"
info "analyzing..."
issues=$(sonarlint "${args[@]}" | sed -ne '/SonarLint Report/,/^---/p')
echo "$issues"

if ! [[ $issues == *"No issues to display"* ]]; then
    fatal "hook abort: some analyses have failed"
fi
