#!/usr/bin/env bash

fatal() {
    echo fatal: "$@" >&2
    exit 1
}

info() {
    echo info: "$@"
}

if [ "$SKIPSONARLINT" ]; then
    info "SKIPSONARLINT is set, skipping verification..."
    exit 0
fi

if ! which sonarlint &>/dev/null; then
    fatal "cannot find sonarlint. Did you add to PATH?"
fi

against=origin/master...
filter=AM  # see --diff-filter in git diff --help

failures=
files=($(git diff --name-only $against --diff-filter=$filter))
for file in "${files[@]}"; do
    if ! [ -f "$file" ]; then
        echo "skip deleted file: $file"
        continue
    fi
    if [[ $file == *src/test/* ]]; then
        echo "skip test file: $file"
        continue
    fi
    if [[ $file == *src/* ]]; then
        echo "analyzing: $file ..."
        issues=$(sonarlint --src "$file" | sed -ne 's/^ *\([0-9][0-9]* issu[a-z]*\).*/\1/p')
        if [ "$issues" ]; then
            echo $issues
            echo "(for more details, run: sonarlint --src \"$file\")"
            failures=1
            echo
        fi
    else
        echo "skip unknown file: $file"
    fi
done

if [ "$failures" ]; then
    fatal "some analyses have failed -> hook abort"
fi
